# FEATURE ENGINEERING

In [1]:
import pandas as pd

In [2]:
data = {
    "salary":[40000,50000,70000,90000,120000],
    "experience":[1,2,4,6,10],
    "height":[170,180,175,165,172],
    "weight":[70,85,75,60,78]
}

In [3]:
df=pd.DataFrame(data)
df

   salary  experience  height  weight
0   40000           1     170      70
1   50000           2     180      85
2   70000           4     175      75
3   90000           6     165      60
4  120000          10     172      78

In [5]:
df["height(m)"]=df["height"]/100
df["bmi"]=df["weight"]/(df["height(m)"]**2)
df

   salary  experience  height  weight  height(m)        bmi
0   40000           1     170      70       1.70  24.221453
1   50000           2     180      85       1.80  26.234568
2   70000           4     175      75       1.75  24.489796
3   90000           6     165      60       1.65  22.038567
4  120000          10     172      78       1.72  26.365603

In [6]:
df["salary_per_experience"]=df["salary"]/df["experience"]
df

,salary,experience,height,weight,height(m),bmi,salary_per_experience
0,40000,1,170,70,1.70,24.221453,40000.0
1,50000,2,180,85,1.80,26.234568,25000.0
2,70000,4,175,75,1.75,24.489796,17500.0
3,90000,6,165,60,1.65,22.038567,15000.0
4,120000,10,172,78,1.72,26.365603,12000.0

In [10]:
df["rank"]=pd.cut(
    df["experience"],
    bins=[0,3,5,7,10],
    labels=["junior","assosiate","senior","lead"]

)
df

,salary,experience,height,weight,height(m),bmi,salary_per_experience,rank
0,40000,1,170,70,1.70,24.221453,40000.0,junior
1,50000,2,180,85,1.80,26.234568,25000.0,junior
2,70000,4,175,75,1.75,24.489796,17500.0,assosiate
3,90000,6,165,60,1.65,22.038567,15000.0,senior
4,120000,10,172,78,1.72,26.365603,12000.0,lead

In [11]:
print(df.corr(numeric_only=True))

                         salary  experience    height    weight  height(m)  \
salary                 1.000000    0.997199 -0.345303 -0.143398  -0.345303
experience             0.997199    1.000000 -0.314748 -0.095728  -0.314748
height                -0.345303   -0.314748  1.000000  0.945991   1.000000
weight                -0.143398   -0.095728  0.945991  1.000000   0.945991
height(m)             -0.345303   -0.314748  1.000000  0.945991   1.000000
bmi                    0.063134    0.123710  0.791626  0.945903   0.791626
salary_per_experience -0.860664   -0.833793  0.094517  0.034148   0.094517

                            bmi  salary_per_experience
salary                 0.063134              -0.860664
experience             0.123710              -0.833793
height                 0.791626               0.094517
weight                 0.945903               0.034148
height(m)              0.791626               0.094517
bmi                    1.000000              -0.013960
salary_per_experience -0.013960               1.000000